### ISSUE TITLE
Is there a new version?

### ISSUE THREAD

**Issue by svendeckers** [diosney/node-sequelize-noupdate-attributes#4]
I'm using sequelize v5.19.6 and this plugin does not work anymore unfortunately.
Will there be an updated version ?

Thanks on beforehand.

**Comment by diosney** [comment]
Sorry, Life as usual stepped in the road and I had to focus on other things, making me unable to dedicate time to a project I didn't used frequently anymore.

If you wanna be promoted to manage this repo just tell me, I will be more than happy to see that even a simple utility like this is maintained and useful for other people.

**Comment by DanielOverdevestPZH** [comment]
Fixed in https://github.com/diosney/node-sequelize-noupdate-attributes/pull/7

**Comment by diosney** [comment]
Sorry it took too long.

I just published a version `2.0.0` that works with Sequelize `>=6.16.0`, at least the compilation phase, since I refactored everything to typescript and some functions and typings from Sequelize are not available until that very version.
