### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by diosney** [diosney/node-sequelize-noupdate-attributes#6]
Sorry, Life as usual stepped in the road and I had to focus on other things, making me unable to dedicate time to a project I didn't used frequently anymore.

If you wanna be promoted to manage this repo just tell me, I will be more than happy to see that even a simple utility like this is maintained and useful for other people.

**Comment by DanielJRaine** [comment]
Hello, I'm interested in maintaining this project. It's my first open-source contribution, but I think it's worth keeping up-to-date.

**Comment by diosney** [comment]
Sorry for the delay , I'm back.
